//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WinFormsGame.Classes.MapClasses
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Path
	{
		public virtual Location StartLocation
		{
			get;
			set;
		}

		public virtual IEnumerable<Cell> Cells
		{
			get;
			set;
		}

		public virtual Location EndLocation
		{
			get;
			set;
		}

	}
}

