//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WinFormsGame.Classes.PowerUpClasses
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;
    using Classes;

	public class Yellow : PowerUp
	{
	}
}

