//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WinFormsGame.Classes.MapClasses
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Cell
	{
		public virtual bool IsWall
		{
			get;
			set;
		}

		public virtual Location Location
		{
			get;
			set;
		}

	}
}

