//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WinFormsGame.Classes.MapClasses
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Location
	{
		public virtual int X { get; set; }
		public virtual int Y { get; set; }

        public Location(int x, int y)
        {
            X = x;
            Y = y;
        }

        public override string ToString()
        {
            return "(" + X + "," + Y + ")";
        }

    }
}

