//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WinFormsGame.Classes.MapClasses;

public class Drawable
{
	public virtual List<Cell> Cells { get; }

	public virtual List<Entity> Entities { get; }

    public Location CenterLocation { get;}

    public Drawable(List<Cell> cells, List<Entity> entities, Location loc)
    {
        Cells = cells;
        CenterLocation = loc;
    }

}

