//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WinFormsGame.Classes.MapClasses;

public class Drawable
{
	public virtual Cell Cells
	{
		get;
		set;
	}

	public virtual Entity Entities
	{
		get;
		set;
	}

}

