//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WinFormsGame.Classes.MapClasses;

/// <summary>
/// Entities that can exist within the game
/// </summary>
/// <remarks>See entity diagram for childs</remarks>
public abstract class Entity
{
	/// <summary>
	/// Amount of hitpoints
	/// </summary>
	public virtual int Hitpoints
	{
		get;
		set;
	}

	public virtual int Damage
	{
		get;
		set;
	}

	public virtual Location Location
	{
		get;
		set;
	}

	public virtual Location Vector
	{
		get;
		set;
	}

}

