//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using WinFormsGame.Classes.EntityClasses;

public class Level
{
	public virtual int LevelNumber
	{
		get;
		set;
	}

	public virtual IEnumerable<Enemy> Enemies
	{
		get;
		set;
	}

}

