//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WinFormsGame.Classes
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    using MapClasses;

    public class Map
	{
        private Settings settings;

		public virtual List<Cell> Cells { get; private set; }

		public Map(Settings settings)
		{
            this.settings = settings;
		}

		public virtual Path CalculatePath(Location startLoc, Location EndLoc)
		{
			throw new System.NotImplementedException();
		}

	}
}

