//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Settings
{
	public virtual int VerticalCells
	{
		get;
		set;
	}

	public virtual int HorizontalCells
	{
		get;
		set;
	}

	public virtual int CellSize
	{
		get;
		set;
	}

	public virtual int GameWidth
	{
		get;
		set;
	}

	public virtual int GameHeight
	{
		get;
		set;
	}

	public virtual int Seed
	{
		get;
		set;
	}

	public virtual int ViewHeight
	{
		get;
		set;
	}

	public virtual int ViewWidth
	{
		get;
		set;
	}

}

